version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8001"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
